export default{
    //User actions
    //Create user
    CREATE_USER_SET_USER_NAME: 'CREATE_USER_SET_USER_NAME',
    CREATE_USER_SET_PASSWORD: 'CREATE_USER_SET_PASSWORD',
    CREATE_USER_REQUEST: 'CREATE_USER_REQUEST',
    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAIL: 'CREATE_USER_FAIL',
    //Create token
    CREATE_TOKEN_SET_USER_NAME: 'CREATE_TOKEN_SET_USER_NAME',
    CREATE_TOKEN_SET_PASSWORD: 'CREATE_TOKEN_SET_PASSWORD',
    CREATE_TOKEN_REQUEST: 'CREATE_TOKEN_REQUEST',
    CREATE_TOKEN_SUCCESS: 'CREATE_TOKEN_SUCCESS',
    CREATE_TOKEN_FAIL: 'CREATE_TOKEN_FAIL',
    CREATE_TOKEN_RESET: 'CREATE_TOKEN_RESET',
    //Get To Do list
    GET_TODOS_REQUEST: 'GET_TODOS_REQUEST',
    GET_TODOS_SUCCESS: 'GET_TODOS_SUCCESS',
    GET_TODOS_FAIL: 'GET_TODOS_FAIL',
    //Add, update and delete To Do in todosList
    GET_TODOS_ADD_TODO: 'GET_TODOS_ADD_TODO',
    GET_TODOS_EDIT_TODO: 'GET_TODOS_EDIT_TODO',
    GET_TODOS_REMOVE_TODO: 'GET_TODOS_REMOVE_TODO',
    //Add To Do to postTodo state
    POST_TODO_SET_TITLE: 'POST_TODO_SET_TITLE',
    POST_TODO_SET_CONTENT: 'POST_TODO_SET_CONTENT',
    POST_TODO_SET_DUE_DATE: 'POST_TODO_SET_DUE_DATE',
    //Post To Do to endpoint
    POST_TODO_REQUEST: 'POST_TODO_REQUEST',
    POST_TODO_SUCCESS: 'POST_TODO_SUCCESS',
    POST_TODO_FAIL: 'POST_TODO_FAIL',
    //Add To Do to putTodo state
    PATCH_TODO_SET_DATA: 'PATCH_TODO_SET_DATA',
    PATCH_TODO_SET_TITLE: 'PATCH_TODO_SET_TITLE',
    PATCH_TODO_SET_CONTENT: 'PATCH_TODO_SET_CONTENT',
    PATCH_TODO_SET_DUE_DATE: 'PATCH_TODO_SET_DUE_DATE',
    //Put To Do to endpoint
    PATCH_TODO_REQUEST: 'PATCH_TODO_REQUEST',
    PATCH_TODO_SUCCESS: 'PATCH_TODO_SUCCESS',
    PATCH_TODO_FAIL: 'PATCH_TODO_FAIL',
    //Delete To Do from endpoint
    DELETE_TODO_REQUEST: 'DELETE_TODO_REQUEST',
    DELETE_TODO_SUCCESS: 'DELETE_TODO_SUCCESS',
    DELETE_TODO_FAIL: 'DELETE_TODO_FAIL',
    //Filter todosList
    FILTER_TODOS_BY: 'FILTER_TODOS_BY',
    //Change Application theme from dark to light
    TOGGLE_APPLICATION_THEME: 'TOGGLE_APPLICATION_THEME'
};